version: '3.8'

services:
  adminer:
    image: adminer:4.8.1
    container_name: adminer-ocvt
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
      - ADMINER_PLUGINS=${ADMINER_PLUGINS}
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
      - ADMINER_DISABLE_SESSIONS=${ADMINER_DISABLE_SESSIONS}
    networks:
      - mynetwork
    expose:
      - "${ADMINER_PORT}"
    restart: unless-stopped

  nginx:
    image: nginx:1.25
    container_name: nginx-adminer-ocvt
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - ./nginx/conf.d:/etc/nginx/templates:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "${NGINX_PORT}:443"
    environment:
      - ADMINER_PORT=${ADMINER_PORT}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
    networks:
      - mynetwork
    depends_on:
      - adminer
    restart: unless-stopped

networks:
  mynetwork:
    external: true
