GRANT ALL PRIVILEGES ON DATABASE my_database TO admin;
ALTER USER admin WITH SUPERUSER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO admin;
